# Generated by Django 2.2.16 on 2022-02-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200118_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notifications_type',
            field=models.IntegerField(choices=[(1, 'Welcome'), (2, 'Alert')], default=False),
        ),
    ]
