# Generated by Django 2.2.16 on 2022-02-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_notifications_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notifications_type',
            new_name='notification_type',
        ),
    ]
