# Generated by Django 2.2.16 on 2022-02-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20220226_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Welcome', 'Welcome'), ('Alert', 'Alert')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
